#!/bin/sh
set -e

export TEXTDOMAINDIR=/usr/share/locale
export TEXTDOMAIN=aliedit-installer

curdir=`pwd`


if [ -e $HOME/.mozilla/plugins/libaliedit*.so ]; then
	zenity --question --text="`gettext \"Do you want to uninstall aliedit plugin?\"`" --title="`gettext \"Uninstall\"`"
	if [ "$?" = 0 ]; then
		rm -rf ~/.aliedit
		rm ~/.mozilla/plugins/libaliedit*.so
	fi
	zenity --info --text="`gettext \"Uninstallation completed.\"`" --title="`gettext \"Uninstallation completed.\"` "
else
	zenity --question --text="`gettext \"Do you want to install aliedit plugin?\"`" --title="`gettext \"Install ?\"`"
	tmpdir=`mktemp -d --suffix=aliedit-installer`
	cd $tmpdir
	curl https://securitycenter.alipay.com/sc/aliedit/intro.htm > intro.htm
	url=`grep "https://download.alipay.com/alipaysc/linux/aliedit/" ./intro.htm | grep "img src"| \
	    sed "s/.*\(https:\/\/download.alipay.com\/alipaysc\/linux\/aliedit\/1.0.3.20\/aliedit.tar.gz\).*/\1/"`
	curl $url > aliedit.tar.gz
	tar zxf aliedit.tar.gz
	sh $tmpdir/aliedit.sh&
	sleep 3
	cd $curdir
	rm -rf $tmpdir
	zenity --info --text="`gettext \"Installation completed! To uninstall, re-run this program.\"`" --title="`gettext \"Install completed\"`"
fi
