#!/bin/sh
set -e

export TEXTDOMAINDIR=/usr/share/locale
export TEXTDOMAIN=aliedit-installer

curdir=`pwd`


if [ -e $HOME/.mozilla/plugins/libaliedit*.so ]; then
	zenity --question --text="`gettext \"Are you sure to uninstall aliedit plugins?\"`" --title="`gettext \"To Uninstall aliedit ?\"`"
	if [ "$?" = 0 ]; then
		rm -rf ~/.aliedit
		rm ~/.mozilla/plugins/libaliedit*.so
	fi
	zenity --info --text="`gettext \"Aliedit uninstalling done\"`" --title="`gettext \"Uninstalling done\"` "
else
	zenity --question --text="`gettext \"Are you sure to install aliedit?\"`" --title="`gettext \"To install aliedit ?\"`"
	tmpdir=`mktemp -d --suffix=aliedit-installer`
	cd $tmpdir
	curl https://securitycenter.alipay.com/sc/aliedit/intro.htm > intro.htm
	url=`grep "https://download.alipay.com/alipaysc/linux/aliedit/" ./intro.htm | grep "img src"| \
	    sed "s/.*\(https:\/\/download.alipay.com\/alipaysc\/linux\/aliedit\/1.0.3.20\/aliedit.tar.gz\).*/\1/"`
	curl $url > aliedit.tar.gz
	tar zxf aliedit.tar.gz
	sh $tmpdir/aliedit.sh &
	sleep 3
	cd $curdir
	rm -rf $tmpdir
	zenity --info --text="`gettext \"Aliedit installing done! To uninstall, rerun this program.\"`" --title="`gettext \"Install done\"`"
fi
